import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]
[cursor.style]
blinking = "On"
shape = "Beam"

[font]
size = 11

[font.normal]
family = "JetBrainsMono NFM"
style = "Regular"

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/usr/bin/zsh"

[window]
opacity = 0.96
